//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JA_mod_tool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JA_mod_tool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap crop {
            get {
                object obj = ResourceManager.GetObject("crop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16
        ///18
        ///20
        ///22
        ///24
        ///60
        ///62
        ///64
        ///66
        ///68
        ///70
        ///71
        ///72
        ///74
        ///78
        ///80
        ///82
        ///84
        ///86
        ///88
        ///90
        ///93
        ///96
        ///97
        ///98
        ///99
        ///100
        ///101
        ///103
        ///104
        ///105
        ///106
        ///107
        ///108
        ///109
        ///110
        ///111
        ///112
        ///113
        ///114
        ///115
        ///116
        ///117
        ///118
        ///119
        ///120
        ///121
        ///122
        ///123
        ///124
        ///125
        ///126
        ///127
        ///128
        ///129
        ///130
        ///131
        ///132
        ///136
        ///137
        ///138
        ///139
        ///140
        ///141
        ///142
        ///143
        ///144
        ///145
        ///146
        ///147
        ///148
        ///149
        ///150
        ///151
        ///152
        ///153
        ///154
        ///155
        ///156
        ///157
        ///158
        ///159
        ///160
        ///161
        ///162
        ///163
        ///164
        ///165
        ///166
        ///167
        ///168
        ///169
        ///170
        ///171
        ///172
        ///174
        ///176
        ///178
        ///180
        ///182
        ///184
        ///186
        ///188
        ///190
        ///192
        ///194
        ///195
        ///196 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string itemIDs {
            get {
                return ResourceManager.GetString("itemIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wild Horseradish
        ///Daffodil
        ///Leek
        ///Dandelion
        ///Parsnip
        ///Emerald
        ///Aquamarine
        ///Ruby
        ///Amethyst
        ///Topaz
        ///Jade
        ///Trimmed Lucky Purple Shorts
        ///Diamond
        ///Prismatic Shard
        ///Cave Carrot
        ///Quartz
        ///Fire Quartz
        ///Frozen Tear
        ///Earth Crystal
        ///Coconut
        ///Cactus Fruit
        ///Torch
        ///Dwarf Scroll I
        ///Dwarf Scroll II
        ///Dwarf Scroll III
        ///Dwarf Scroll IV
        ///Chipped Amphora
        ///Arrowhead
        ///Ancient Doll
        ///Elvish Jewelry
        ///Chewing Stick
        ///Ornamental Fan
        ///Dinosaur Egg
        ///Rare Disc
        ///Ancient Sword
        ///Rusty Spoon
        ///Rusty Spur
        ///Rusty Cog
        ///Chicken Statue
        ///Ancient Seed [rest of string was truncated]&quot;;.
        /// </summary>
        public static string itemNames {
            get {
                return ResourceManager.GetString("itemNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Stardew_Valley {
            get {
                object obj = ResourceManager.GetObject("Stardew_Valley", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
